#!/usr/bin/env bash

TARGET_STRING=${1}
TARGET_FILE=${2}

# 第二引数が空なら全ファイル検索
[[ -z ${TARGET_FILE} ]] && TARGET_FILE="*"

if [[ -z ${TARGET_STRING} ]]; then
  cat <<'EOF'
*** command line parameter required ***
ffg <target string> <target file>
EOF
  exit 1
fi

files=($(sudo find $(pwd) -name "${TARGET_FILE}" -type f 2>/dev/null))

echo 'search through '"${#files[@]}"' files'

for ((i = 0; i < ${#files[@]}; i++)); do
  if grep -q "${TARGET_STRING}" "${files[${i}]}"; then
    echo '#####################################################'
    echo Target file: "${files[${i}]}"
    echo '#####################################################'
    cat "${files[${i}]}" | grep --color=auto -C 3 "${TARGET_STRING}"
    echo
  fi
done
